version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: mysql
    hostname: mysql
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: streama_root_password
      MYSQL_USER: streama
      MYSQL_DATABASE: streama
      MYSQL_PASSWORD: streama_password

volumes:
  db_data: