version: "3"

services:
  streama:
    image: streama
    build: .
    restart: always
    container_name: streama
    hostname: streama
    expose:
      - 8080
    volumes:
      - ./videos:/data/streama # Change to your video folder
      - app_data:/app/streama
    environment:
      ACTIVE_PROFILE: mysql
      MYSQL_HOST: <mysql_ip>
      MYSQL_PORT: 3306
      MYSQL_DB: streama
      MYSQL_USER: streama
      MYSQL_PASSWORD: streama_password

volumes:
  app_data: